services:
  rsync:
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID
      - SYS_CHROOT
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
      - ./keys/host:/var/rsync/host
      - ./keys/clients:/var/rsync/clients:ro
