name: test
on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  rsync-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker compose version

      - name: Build & Up
        run: |
          make keys data
          docker compose -f docker-compose.test.yml up -d --build --wait

      - name: Run tests
        run: bash scripts/run.sh

      - name: Logs on failure
        if: failure()
        run: make logs

      - name: Tear down
        if: always()
        run: make down
